version: '3'

services:
  application:
    image: build/application
    build: ./application
    volumes:
      - ./application:/application/electron-dist
      - ./node_modules:/application/node_modules
    depends_on:
      - wasm
  wasm:
    image: build/wasm
    build: ./webassembly
    volumes:
      - ./build:/wasm/build
